print('==================Task 4.1===============')
d1={"customer name":["shoaib","hamad","rehan","abdul","hamza","adil","furqan","rizwan","danish","aamir"]}
d2={"height":['5','6''5','7','4','5','6','4','6','7']}
d3={'contact nmber':['43689','43654983','84379345','349618765','9834690'
    ,'3627887','834629','734684','63498','87436']}
print(type(d1),type(d2),type(d3))
print(d1,d2,d3)
#we can also do by this method
d4={"clients":{"customer name":'shoaib','height':'6','contact':'4759656'}}
print(d4)
print('===================Task4.2===============')
'''
Design an online admission for Skillvention. The fields are same as mentioned in
the admission form'''
print("skillvention")
a1 = input('please sir enter your name')
print(a1)
a2 = input('your father name')
print(a2)
a3 = int(input('enter your Date of birth'))
print(a3)
a4 = input('enter your present address')
print(a4)
a5 =input('enter your Religion')
print(a5)
a6 = input('enter your course')
print(a6)
a7 = int(input('enter your contact number'))
print(a7)
a8 = input('enter your email')
print(a8)
a9 = input('enter your gender')
print(a9)
a10 = input('enter your qualification')
print(a10)
a11 = input('enter your skill')
print(a11)
a12 = input('enter your martial status')
print(a12)
a13 = input('enter fee payment mode')
print(a13)
a14 = input('enter your parents confirmation by sign')
print(a14)
'''Task 3
Create a login and registration form for your website "Python Agency'''
print('============Task 4.3===========')
print("sign up")
a1 = input('enter your first name',)
print(a1)
a2 = input('enter your last name')
print(a2)
a3 = input('enter your username')
print(a3)
a4 = input('enter your password')
print(a4)
a5 = input('confirm your password')
print(a5)
a6 = input('press on next button')
print(a6)
a7 = int(input('enter your phone number'))
print(a7)
a8 = int(input('enter your code'))
print(a8)
a9 = int(input('enter your date of birth'))
print(a9)
a10 = input('enter your gender')
print(a10)
a11 = input('cancel or agree')
print(a11)
